# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hyprland.org/Configuring for more information

#
# Environment
env = VOLUME_BOOST,true
env = VOLUME_BOOST_LIMIT,150
env = NO_AT_BRIDGE,1

#
# Startup helpers
exec-once = env XDG_CONFIG_HOME=$HOME/.config XDG_CONFIG_DIRS= dex --autostart --environment Hyprland
exec-once = dbus-update-activation-environment --systemd --all WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE
exec-once = /usr/bin/gnome-keyring-daemon --start --components=secrets

#
# General layout
#
general {
    gaps_in = 3
    gaps_out = 3
    border_size = 2
    layout = scrolling
}

#
# Input
# Uncomment to enable // change to a preferred value
# 🔗 See https://wiki.hyprland.org/Configuring/Variables/#input
input {
    # kb_layout = us
    follow_mouse = 1
    mouse_refocus = true
    # sensitivity = 0
    # force_no_accel = 0
    # accel_profile = flat 
    numlock_by_default = true
    repeat_delay = 500
    repeat_rate  = 50
    kb_options = caps:none

    # 🔗 See https://wiki.hyprland.org/Configuring/Variables/#touchpad
    touchpad {
        natural_scroll = yes
        scroll_factor = 0.45
    }
}

#
# Gestures
# 🔗 See https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
#     workspace_swipe = true
#     workspace_swipe_fingers = 3
}
gesture = 3, horizontal, unset

#
# Plugins
#
scrolling {
  column_width = 0.9
  fullscreen_on_one_column = true
  follow_focus = true
}

#
# Misc
# For window swallow similar to devour
misc {
    # enable_swallow = true
    # swallow_regex = (foot|kitty|allacritty|Alacritty|ghostty|Ghostty|org.wezfurlong.wezterm)
}

#
# Ecosystem
# Don't show update on first launch
ecosystem {
  # no_update_news = true
}
